project:
  type: book
  output-dir: docs
  # output-file: docs
  # output-dir: pdf_doc
  # output-file: pdf_doc
  # 
book:
  title: "R am IAB"
  author: "Andreas Filser"
  date: last-modified
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_intro.qmd
    - 03_desc.qmd
    # - 04_viz.qmd
    # - 05_data_wrangle1.qmd
    # - 06_data_wrangle2.qmd
    # - 07_inferenz.qmd
    # - 09_reg.qmd
    # - 09_reg2.qmd
    # - 10_log_reg.qmd
    # - 11_data_wrangle3.qmd
    # - 12_apply_loop.qmd
    # - 14_tabellenexport.qmd
    # - 15_RMarkdown.qmd
    # - 17_errors.qmd
    - references.qmd
  language: de-DE
  # downloads: [pdf]
  page-footer:
   center: |
      Alle Kursinhalte {{< fa brands creative-commons >}} 2023 von [Andreas Filser](https://afilser.netlify.app/)<br>
      [CC Lizenz mit Namensnennung {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}](https://creativecommons.org/licenses/by-nc/4.0/)<br>
      Erstellt mit {{< fa brands r-project >}}, Code [hier einsehbar {{< fa brands github >}}](https://github.com/filius23/R_IAB)
      
      


bibliography: references.bib

format:
  html:
    theme: flatly
    page-layout: full
    css: style.css
  # pdf:
  #   documentclass: scrreprt # kapitel02 kable

execute:
  freeze: auto
